// `.env.json` is generated by the `npm run build` command

export const environment = {
  production: true,
  version: '1.0 (prod)',
  serverUrl: 'https://banistmo-back.herokuapp.com',
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    'es-ES',
    'fr-FR'
  ]
};
